"""empty message

Revision ID: 9703d8ea38ec
Revises: 
Create Date: 2024-11-04 16:00:58.548899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9703d8ea38ec'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'forms', ['id'])
    op.create_unique_constraint(None, 'metatags', ['address'])
    op.create_unique_constraint(None, 'products', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='unique')
    op.drop_constraint(None, 'metatags', type_='unique')
    op.drop_constraint(None, 'forms', type_='unique')
    # ### end Alembic commands ###
