"""empty message

Revision ID: fdebf3ada32d
Revises: b3b44cc8a37c
Create Date: 2025-01-08 17:54:39.488099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdebf3ada32d'
down_revision: Union[str, None] = 'b3b44cc8a37c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_precategory',
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('precategory_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['precategory_id'], ['preCategoryProducts.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'precategory_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_precategory')
    # ### end Alembic commands ###
